### ISSUE TITLE
Facing issue while doing pip install Issue with '-march=native'

### ISSUE THREAD

**Issue by Rohit-0710** [iamDecode/sklearn-pmml-model#41]
clang: error: the clang compiler does not support '-march=native'
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sklearn-pmml-model
Failed to build sklearn-pmml-model
ERROR: Could not build wheels for sklearn-pmml-model, which is required to install pyproject.toml-based projects

**Comment by iamDecode** [comment]
Thanks for your report. For most platforms we provide prebuilt python wheels which prevents users from needing to compile the cython code themselves. You seem to be running a platform that no wheels are provided for. Can you share what operating system you're running and what the architecture of your processor is?

**Comment by Rohit-0710** [comment]
I am using macOS with M1 chip.
BTW do you know of any open source library which I can take advantage of to visualize pmml file(Like how a binary tree looks)... Thanks in advance

**Comment by iamDecode** [comment]
I see, Apple silicon machines were not yet included in the wheel builds, but I will make sure to include it soon.

As for a library to visualise PMML, I am not aware of any library doing that. I suppose it would depend a lot on which type of model you would like to visualize. As soon as you get this library to work, you should be able to use any visualization for sklearn models on the models you import through this library though :)

**Comment by iamDecode** [comment]
@Rohit-0710 I pushed some changes on master that should fix building on M1 machines. In addition, I uploaded some wheels to pypi such that `pip install` should work without compiling for you. Can you give it a try? (it may take a while for the new version to show up in pip, if it doesn't work, please try again in a day or so).

**Comment by Rohit-0710** [comment]
@iamDecode Thank you for the resolution as of now it's still failing with the same error when I am doing pip install... I will try tomorrow as well and let you know.

**Comment by iamDecode** [comment]
Great. Perhaps using `pip install --no-cache-dir sklearn-pmml-model` helps to ensure you get the recently built wheels.

**Comment by Rohit-0710** [comment]
Hi It worked I am able to install successfully. Thank you bro for your help... I have sent you a request on linkedin (Name- Rohit Arora) will appreciate it if you would accept..
Thanks.
